version: '2'

services:
  postgresql-master:
    image: 'bitnami/postgresql:15.8.0'
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=root
      - POSTGRESQL_PASSWORD=rootpassword
      - POSTGRESQL_DATABASE=testdb
