version: '2'

services:
  postgresql-master:
    image: 'bitnami/postgresql:15.8.0'
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=root
      - POSTGRESQL_PASSWORD=rootpassword
      - POSTGRESQL_DATABASE=testdb
  redis-master:
    image: 'bitnami/redis:7.0.11'
    ports:
      - "6379:6379"
    environment:
      # - REDIS_PASSWORD=123456
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL