spring:
  application:
    name: dessert_atelier
  profiles:
    include: 
      - oauth
      - jwt
    active:
      - postgresql-test

server:
  servlet:
    session:
      tracking-modes: cookie

