server:
  port: 8070

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/testdb
    username: root
    password: rootpassword

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto:
        none
    properties:
      hibernate:
        '[format_sql]': true

  sql:
    init:
      mode: 
        # never
        always
      data-locations: classpath:sql/test-data-postgresql.sql
