spring:
  application:
    name: dessert_atelier
  profiles:
    include: 
      - oauth
      - jwt
      - aws
      - redis
    active:
      - postgresql-test
  servlet:
    multipart:
      enabled: false
      max-file-size: 10MB
      max-request-size: 10MB