spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto:
        none
    properties:
      hibernate:
        '[format_sql]': true

  sql:
    init:
      mode: always
      data-locations: classpath:sql/test-data-h2.sql