
spring:
    security:
        oauth2:
            client:
                registration:
                ## Google Oauth 설정
                    google:
                        client-id: 
                        client-secret: 
                        redirect-uri: 
                        scope: 
                ## Naver OAuth 설정
                    naver:
                        client-id: 
                        client-secret: 
                        redirect-uri: 
                        authorization-grant-type: 
                        scope: 
                ## Kakao OAuth2 프로바이더 설정
                provider:
                ## Naver OAuth2 프로바이더 설정
                    naver:
                        authorization-uri: 
                        token-uri: 
                        user-info-uri: 
                        user-name-attribute: 
